1. Вкладник поклав 50000 умовних одиниць на три різні рахунки в три різні банки. За першим рахунком виплати становитимуть 5% річних, по другому – 7% річних та по третьому 6% річних. Відомо, що через рік вкладник отримав за відсотками суму в 2250 у.о. з першого та другого банку та суму в 1400 у.о. з першого та третього банку. Скільки умовних одиниць він поклав на кожен рахунок спочатку?

In [5]:
import numpy as np


matrix_A = np.array([[1, 1, 1],
                     [0.05, 0.07, 0],
                     [0.05, 0, 0.06]])
matrix_B = np.array([[50000],
                     [2250],
                     [1400]])

A_inverse = np.linalg.inv(matrix_A)
results = A_inverse.dot(matrix_B)
print(results)

[[10000.]
 [25000.]
 [15000.]]


2. На складі зберігаються мобільні телефони iPhone 6, iPhone 11, iPhone 12 моделей. Всього 1328 екземплярів. Моделей iPhone 6 на 120 менше, ніж моделей iPhone 11, та на 100 більше, ніж моделей iPhone 12. Скільки моделей кожного виду на складі?

In [6]:
matrix_A = np.array([[1, 1, 1],
                     [-1, 1, 0],
                     [1, 0, -1]])
matrix_B = np.array([[1328],
                     [120],
                     [100]])
results = np.linalg.solve(matrix_A, matrix_B)
print(results)

[[436.]
 [556.]
 [336.]]


3. Складіть канонічне рівняння еліпсоїда, що проходить через три точки A, B, C.

In [15]:
coordinates = np.array([[3, 0, 3],
                        [6, 1/4, 0],
                        [1, 1/3, 1]])
ones = np.ones((3,1))
res = np.linalg.solve(coordinates, ones)
a_squared = 1/res[0]
b_squared = 1/res[1]
c_squared = 1/res[2]
print(a_squared)
print(b_squared)
print(c_squared)

[12.]
[0.5]
[4.]


4. Складіть рівняння параболи що проходить через задані три точки (1,12), (3,54), (-1,2). Необхідно знайти коефіцієнти рівняння a,b,c.

In [18]:
x_coords = np.array([[1, 1, 1],
                   [9, 3, 1],
                   [1, -1, 1]])
y_coords = np.array([[12],
                     [54],
                     [2]])
params = np.linalg.solve(x_coords, y_coords)
a = params[0]
b = params[1]
c = params[2]
print(a)
print(b)
print(c)

[4.]
[5.]
[3.]


5. Складіть функцію get_polynom, яка за набором точок буде знаходити коефіцієнти багаточлена. Таким чином функція приймає список кортежів з координатами та повертає набір коефіцієнтів.

In [61]:
def get_polynom(coords):
    x = np.array([pair[0] for pair in coords])
    y = np.array([pair[1] for pair in coords])
    vander_matrix = np.vander(x, increasing=True)
    results = np.linalg.solve(vander_matrix, y)
    return results
    

coords = [(0, 0),
          (4, 2),
          (10, 6),
          (12, 6.5)]
coefficients = get_polynom(coords)
print(coefficients)

[ 0.          0.20416667  0.096875   -0.00572917]
